M48
; DRILL file {KiCad 7.0.6} date Fri Aug  4 20:28:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-04T20:28:30-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
%
G90
G05
T1
X5.855Y-4.38
X5.855Y-4.58
T2
X6.01Y-4.4724
X6.01Y-4.5511
T0
M30
